export const CURSOS_UNIFEI = [
  "Administração",
  "Ciência da Computação",
  "Ciências Biológicas Licenciatura",
  "Engenharia Ambiental",
  "Engenharia Civil",
  "Engenharia da Computação",
  "Engenharia de Bioprocessos",
  "Engenharia de Controle e Automação",
  "Engenharia de Energia",
  "Engenharia de Materiais",
  "Engenharia de Produção",
  "Engenharia Elétrica",
  "Engenharia Eletrônica",
  "Engenharia Mecânica",
  "Engenharia Mecânica Aeronáutica",
  "Engenharia Química",
  "Sistemas de Informação",
];

export const CARGOS_COMISSAO = [
  { id: "aderido", label: "Aderido (Apenas Formando)" },
  { id: "presidencia", label: "Presidência" },
  { id: "vice_presidencia", label: "Vice-Presidência" },
  { id: "diretor_tesouraria", label: "Diretor(a) de Tesouraria" },
  { id: "vice_tesouraria", label: "Vice-Diretor(a) de Tesouraria" },
  { id: "membro_tesouraria", label: "Membro de Tesouraria" },
  { id: "diretor_secretaria", label: "Diretor(a) de Secretaria" },
  { id: "vice_secretaria", label: "Vice-Diretor(a) de Secretaria" },
  { id: "membro_secretaria", label: "Membro de Secretaria" },
  { id: "diretor_eventos", label: "Diretor(a) de Eventos" },
  { id: "vice_eventos", label: "Vice-Diretor(a) de Eventos" },
  { id: "membro_eventos", label: "Membro de Eventos" },
  { id: "diretor_marketing", label: "Diretor(a) de Marketing" },
  { id: "vice_marketing", label: "Vice-Diretor(a) de Marketing" },
  { id: "membro_marketing", label: "Membro de Marketing" },
  { id: "diretor_rh", label: "Diretor(a) de RH" },
  { id: "vice_rh", label: "Vice-Diretor(a) de RH" },
  { id: "membro_rh", label: "Membro de RH" },
  { id: "admin", label: "Administrador do Sistema" },
];
